src/django_exercise/django_exercise/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('auth/',include("users.urls")),
    path('oauth/', include('social_django.urls', namespace='social')),  # <-- here
]

src/django_exercise/users/urls.py
from django_exercise.urls import path
from . import views

app_name = "user"
urlpatterns = [
    path("login", views.login_view, name="login"),
    path("logout",views.logout_view, name="logout"),
    path("signup",views.signup_view, name="signup")
]

src/django_exercise/polls/models.py
from django.db import models

# Create your models here.

src/django_exercise/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    student_id = models.CharField(max_length=10)
    
    
    

src/django_exercise/polls/views.py
from django.shortcuts import render

# Create your views here.

src/django_exercise/users/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate,login,logout
from django.shortcuts import redirect
from .models import User
# Create your views here.
def login_view(request):
    if request.method == "POST":
        username = (request.POST["username"])
        password = (request.POST["password"])
        user = authenticate(username=username,password=password)
        if user is not None:
            print("인증성공")
            login(request,user)
        else :
            print("인증실패")
    return render(request,"users/login.html")

def logout_view(request):
    logout(request)
    return redirect("user:login")

def signup_view(request):
    if request.method == "POST":
        print(request.POST)
        username  = request.POST["username"]
        password  = request.POST["password"]
        email  = request.POST["email"]
        favorite  = request.POST["favorite"]
        student_id = request.POST["student_id"]
        gender  = request.POST["gender"]
        
        Department  = request.POST["Department"]

        user = User.objects.create_user(username, email, password)
        user.favorite = favorite
        user.student_id = student_id
        user.gender = gender
        
        user.Department = Department
        user.save()
        return redirect("user:login")
    return render(request, "users/signup.html")

src/django_exercise/users/templates/users/login.html
<br>
{% if user.is_authenticated %}
<html>
    <head>
        <title>Example</title>
    </head>
    <body>
        <p>login succeed</p>
    </body>
    
    <a href="{%url 'user:logout'%}">로그아웃</a>
</html>
{%else%}
<form action="" method="POST">
    {% csrf_token %}
    <input name="username" type="text">
    <input name="password" type="password">
    <input type="submit" value="로그인">
</form>
<a href="{% url 'user:signup' %}">회원가입</a>
{%endif%}

src/django_exercise/users/templates/users/signup.html
<br>

<form action="" method="POST">
    {% csrf_token %}
    <p>아이디</p>
    <input name="username"type="text">
    <p>비밀번호</p>
    <input name="password"type="password">
    <p>이메일 주소</p>
    <input name="email" type="text">
    <p>좋아하는 음식</p>
    <input name="favorite"type="text">
    <p>학번</p>
    <input name="student_id"type="text">
    
    <p>성별</p>
    <input type="radio" id="male" name="gender" value="male">
    <label for="male">남자</label><br>
    <input type="radio" id="female" name="gender" value="female">
    <label for="female">여자</label><br>
    
    <p>학과</p>
    <input name="Department"type="text">
    
    <input type="submit" value="회원가입">

</form>